name: Rodar Previsão de Temperatura do Trilho

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # 06:00 UTC (03:00 BRT)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Rodar script de previsão
        run: python main.py

      - name: Fazer commit do histórico de previsão
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Atualiza histórico de previsão (parquet)"
          file_pattern: "data/rail_prediction_history.parquet"